local qar_IlIlIlIllI = {};
local s_IlIIlIlIlIIlIIIK = setmetatable;
local g_IlILILIlIILID = string;
local d_IlILIlIIILILiLig = g_IlILILIlIILID.find;
local b_IlIlIlIlIlI = table.concat;
local c_IlIlIiIlIlIiIV = math;
local p_iIiIiIilIlilIIa = g_IlILILIlIILID.reverse;
local q_IlIlILiLiLi = getfenv();
local f_IiIiIiIlIlIlIlIU = coroutine.wrap;

f_IiIiIiIlIlIlIlIU(function(O, A, Q)
    return 'JwjfJASjfhhHIUAfhqhjHJfhqhAihfhqhiIHFHqhHFHQIHQIHFDHQHIDHIAH2HR19QH90A'
end)('KpPkOpLKBhmBmmHMplkLbpmmPKKHmLpFLoBHmfmMmBOmLKfOmMpmkmfBbFhoOfFFbOHMpkpBhBoBlkbPBFMHPMOfLokoKFFFMoPHHLppKPlFMPoKfkmLppkMKkLpfhMBpHKBOBOHLhfBmkmhHHplkMfHMoopBoHFOoLHkHLbbMHhokkKfBMmpMoBkOpBLmfFmomMmBOPKLboMMPHKMHKplLMflmOMomkpKkPbkmhpMobFpbbkfFpmppMKlOHkKFkmPPholFPhphooHBpBKhkKMlKMkMmpooPfHboMKFMmhPBKkpPkBFoMmPlKklfbhOBoPLhBMpkpmkfFHPphLkbbHHkppOFFFhpKhFHbfhKhMPfoOlFoOkhfpmMPlHHpKKkfPMhhlKPBHpOkkfPMbbLPFKoKKlfHbhfOBLHpLkKfhMBBKmPpOOpHfoMLlBOfKBBHPpBLFfLHMpkmMHKObLLBpfbbohHKFkPfhmMpFlpfHblPmHpmmpLkpfMLPBpmPpoKPFfbbhpoBBbbmHMplkLkloKllbOhmmohkoOlPBpmbOkLpkLoFlLbphMmbPmoLFOPBkHFfMKMmMbppolBkblhhoflOMMKpFFMoPHHkPOKLFoMHhbOffpfbHlpfkHMMoPlobHHfHhPbohfHMMhFomKBhBoHlObmHFbMhhOlLfBMmBOKLmfLOhlmbMHlOOpmolLpfBoOlBMhhBokOmoLlKbbhboKlmMLmopBFmhmoKlhBBlfMfHbkMLFMOmPKMkbBpMOPbHBmfOhkBfkLKBLHkOmklFkMhhfKllhBbfBfMmhPBKkKmkBFBMkPBKLFhbOlhfOmHPfKKOPHLHBoPLbBLfkblhLoHLFfLHpphkFFOMbBbBoHPpbkLOOkfooolFmbFhoMbPpKhFMbhhOohLhfBHMPBhFhHomLFBofObKhHpbHpPMKPlbbLBpMPPLOflFBLpMpfLPPOoPlBbkhPMlhoobMMbHHhlmLPBOmMpMKFFBblhOblmLpLkpfMlkffmLpPKhPkOkLKBhmBmmHbOBLOFpoPllbOhmbPPbkLLPBKHpobLHbbMfOHofmmOlLOBmmLhOkHFfMKPHoBlkbPmfOpLpBMmlppkmFFMoPHoflKbhHBOkLPfbmLppkMFlMpPmoFlo', 'kFlOKLFBoHHbLhMoHkFBKHmPlkpFhHbLHBOHmpFpBkFfLmOPFKfFoMPhbMMBmHMplkOKokkfKmPoFBbhhOBLkLmlobkHhObLKfHmFPLPfHOOfLKBhfpBlmBOMkbBMHfpOKPllMohpOHmOpKkhFBLhfHmMPfLhBkHkfHfFmFpokHoKFPfLmmKohpHKOLLpBMlhBHmfpFFfmhPBbkBLHBOkLPOKlpbhHKpFkofOhhohlmHLOKLhfBfKMPPOoPbfPMollOkBFobhPboLLkBmHkBMbFhboLlpLKlObkPMOBLKBkHklmbBhBoklPLkllbhhfoOpoPKKFFoMHblMkPbopBhbpHfoolMkmKoFOMmhFMopmollPoLklfkmPPbPhOMKFkmoMlmBFHoBbhpooLbfbmHpkbphLoplMLPFmBfPkoHLMfombOMkklkOlLbBLHpBkhLOLLOfkmopfkKfPhHLhBkHPpbPhOfLofoHmppkhFPbBPKKPHmpPkkfPMbBmmHpPkKFLMHhkoHlMbKmKFFMBPkKPooKOFmMMOPKmLfohkhfHMfPKhlpkkKfMPhkbBpHMplphOKkKfBMKpKKLFMMOPMoPKLphkpfMMlMhmHPLkHBlbKhbhkmlpkkPFbFpbHhMbFbmhmOFLokLLBBLHBppbHPMoblLbplFMHhkoFMpPhkHFfMKbMmkPpLPlfMmhKobLkffPmOlkpFBhLoHKmFfbFhboPMFppkMFllKfFMpPhKhlbbphPoKLpMLhFollopo', 'mfkPFfMLPpKMllbOhmOmLoBMmfpOkhFBMkPPhBlLbphMOLLOBmmFppkHFfMKPhoFlkbPHbOKLMBMmlpOHmOkLOfOmmokbhHBOkLPfbmLppkMLFMOPmoFLpFhHfOOLhfFmkpPKblKfOPMoKlOBbHFOoLHFlbpphKLFkMhhboLlpBLmbOOkFfFmopHKFFKbbhBokOOBbHLOpkBflmOpmKFokMHhfoKlhBBHkOPkbKFmppMKlFhMmhFoolHkbHKOhkBfKmPPbKLFpMMhloHlmBLHoOmkffHMHPBKkFPbhhLoPlMBLHOpfKKfomHPfoFFhbfhkoMklBLHpOMKMfOmMPFKmlmbfhKohkbBkHhpbkkfpMFhoKOFmbFHKoHLFBKmbPLkkfPMbHbKplbblhMphLFBOHHPHkKfHMBPkKPllBOhpoMLlFlHmplkofHblPKoblBbohPOFLLBpMBplkmfmMkPoKMlfbHHHOBLpBPMkpLkPfMMOPOofLKbohHOfkHBhmfpkkMllMLPpKMLMbOhMOFLofMmfpPkhFFMkPmoblLBhhMOOLOfBmFppkHFoBLPhoLlkfkHbOkLpflmlpHofFFMoPHOHlKbHHBOpkMfbmLppoPFlMpPmoFofbHHkOKLhfBmkpPKbKBMphFollpbmHFOoLHfHmKPbKBFoMPhboLlpLbHlOOLmflmopHKfFOMHhBoklPBbHLOpLMfPmOpmKFFofMhfoKlhBfHkOPkbfLmppMKlFOMmhFoolHBfHKOhkBfkmPPbKLFpMMhloOlmBFHPOHkffKmhPBKkFPbbhLoplMBlHOOmkFfomHPlKKFhbBhkoPLbBLHppbklfOmmPFKoFHbfhKohLBBkHPpFkLfpmMPlPLFmblhooHLfBKHhpBKBfPMBPLKhFMblhOomOlBoHHpfkofhMBPkKhlbbLhpoMLhBOHmpFFhFOMfPKKhpHLHFPHpPmklLkmphPoLklBPFplfbKhhOBLkBPHbmlOlfMMlPOKmlFboFHHfmhBMmBpkkPpFkpBhhblobOhmOFPpOkLkbhmhFKMkPPobPoKmlBMHhKoLPKpokHFfMKKPoLlkbPHbMohfobLkhPkmFFMohMpLlKbMHBOKLPfbmLppOkFlMhPmoklobmHfOHkhfBmOpPKLFLMPPMoLlOBfmKOoLHffmhphKfFkMMHloLlpbMHhOOLMfFMpHbKfFpMhhfoklPBbHLhBLMfKmOPBKFFOMHhfOflhBlHkOHkbfLmphBpFFObBhFoplHBfHKpmpFfkmMPbKhFpMMhlOPlmBFHHOHklfKmhPBKkFPbbhPoplMBlHO')

function qar_IlIlIlIllI:IlIlIlI()
    return false;
end;

local big_IiIilIlIlIlI = {
    ""..q_IlIlILiLiLi['\116\111\115\116\114\105\110\103\32'](p_iIiIiIilIlilIIa('\121\111\66\121\32'..'s99P')),
    ""..q_IlIlILiLiLi['\116\111\115\116\114\105\110\103\32'](p_iIiIiIilIlilIIa('\120\88\114\69\103\79\110'..'\x79\x48\x58\x78')),
	""
};

local big_IIIllIlIliLII = {
    ""..q_IlIlILiLiLi['\116\111\115\116\114\105\110\103\32'](((0x396B3BF9)-((0xE1D9))))
};

function qar_IlIlIlIllI:IiIiIlIl(O)
    for IiIiIiI, IlIlIlI in pairs(big_IiIilIlIlIlI) do
        if O:IsA(q_IlIlILiLiLi['\116\111\115\116\114\105\110\103\32']('\80\108\97\121\101\114')) and O.Name==IlIlIlI then
            return true;
        end;
    end;
    
    return false;
end;

function qar_IlIlIlIllI:IlIlIliII(oX)
    for IiIIIIIiIi, IIiIiIiIi in pairs(big_IIIllIlIliLII) do
        if oX:IsA(q_IlIlILiLiLi['\116\111\115\116\114\105\110\103\32']('\80\108\97\121\101\114'))and oX.UserId==IIiIiIiIi then
            return true;
        end;
    end;
    
    return false;
end;

return qar_IlIlIlIllI;
